# Generated by Django 5.2.10 on 2026-04-07 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vessel_cargo_type_vessel_destination_vessel_eta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_on_position_change', models.BooleanField(default=True)),
                ('alert_on_status_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='core.vessel')),
            ],
            options={
                'unique_together': {('user', 'vessel')},
            },
        ),
    ]
