# Generated by Django 5.2.10 on 2026-04-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='port',
            name='arrivals_24h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='port',
            name='avg_wait_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='port',
            name='congestion_level',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='port',
            name='departures_24h',
            field=models.IntegerField(default=0),
        ),
    ]
