# Generated by Django 5.2.10 on 2026-04-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_is_active_port_arrivals_24h_port_avg_wait_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fleet_size', models.IntegerField(default=0)),
                ('hq_location', models.CharField(blank=True, max_length=100, null=True)),
                ('utilization_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='vessel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessels', to='core.company'),
        ),
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Passed', max_length=20)),
                ('performed_by', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_usd', models.FloatField(default=1000.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('coverage_details', models.TextField(blank=True, null=True)),
                ('last_renewal', models.DateField(auto_now_add=True)),
                ('vessel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='core.vessel')),
            ],
        ),
    ]
